/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "proto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(proto_question, proto_question, 2)


PB_BIND(proto_answer, proto_answer, 2)



