/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_IGN_IGN_PB_H_INCLUDED
#define PB_IGN_IGN_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _ign_EventType {
    ign_EventType_UNSPECIFIED = 0,
    ign_EventType_HEARTBEAT = 1,
    ign_EventType_LOCK_LOG = 2,
    ign_EventType_GET_USER_INFO = 3,
    ign_EventType_UPDATE_LOCK_LIST = 4,
    ign_EventType_ADD_LOCK = 5,
    ign_EventType_GET_JOBS = 6,
    ign_EventType_UPDATE_JOB = 7,
    ign_EventType_DEMO_UPDATE_LOCK_BATTERY = 8,
    ign_EventType_DEMO_UPDATE_LOCK_STATUS = 9,
    ign_EventType_DEMO_UPDATE_LOCK_ACTIVITIES = 10,
    ign_EventType_UPDATE_USER_INFO = 128,
    ign_EventType_LOCK_JOB = 129,
    ign_EventType_NEW_JOB_NOTIFY = 130
} ign_EventType;

typedef enum _ign_OSType {
    ign_OSType_UKNOWN = 0,
    ign_OSType_LINUX = 1,
    ign_OSType_RTOS = 2
} ign_OSType;

typedef enum _ign_DemoLockCommand {
    ign_DemoLockCommand_UNSPECIFIED_DLC = 0,
    ign_DemoLockCommand_UNLOCK = 1,
    ign_DemoLockCommand_LOCK = 2,
    ign_DemoLockCommand_CREATE_PIN = 3,
    ign_DemoLockCommand_DELETE_PIN = 4,
    ign_DemoLockCommand_GET_BATTERY = 5,
    ign_DemoLockCommand_GET_LOCK_STATUS = 6,
    ign_DemoLockCommand_GET_LOGS = 7
} ign_DemoLockCommand;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(100) ign_BridgeProfile_bt_id_t;
typedef PB_BYTES_ARRAY_T(100) ign_BridgeProfile_mac_addr_t;
typedef PB_BYTES_ARRAY_T(100) ign_BridgeProfile_local_ip_t;
typedef PB_BYTES_ARRAY_T(100) ign_BridgeProfile_public_ip_t;
typedef PB_BYTES_ARRAY_T(100) ign_BridgeProfile_sys_statics_t;
typedef PB_BYTES_ARRAY_T(100) ign_BridgeProfile_wifi_ssid_t;
typedef PB_BYTES_ARRAY_T(100) ign_BridgeProfile_name_t;
typedef struct _ign_BridgeProfile {
    ign_OSType os_info;
    ign_BridgeProfile_bt_id_t bt_id;
    ign_BridgeProfile_mac_addr_t mac_addr;
    ign_BridgeProfile_local_ip_t local_ip;
    ign_BridgeProfile_public_ip_t public_ip;
    ign_BridgeProfile_sys_statics_t sys_statics;
    ign_BridgeProfile_wifi_ssid_t wifi_ssid;
    int32_t wifi_signal;
    uint32_t inited_time;
    ign_BridgeProfile_name_t name;
} ign_BridgeProfile;

typedef PB_BYTES_ARRAY_T(100) ign_DemoLockJob_pin_t;
typedef struct _ign_DemoLockJob {
    char bt_id[100];
    ign_DemoLockCommand op_cmd;
    ign_DemoLockJob_pin_t pin;
} ign_DemoLockJob;

typedef PB_BYTES_ARRAY_T(500) ign_DemoUpdateLockActivities_log_t;
typedef struct _ign_DemoUpdateLockActivities {
    ign_DemoUpdateLockActivities_log_t log;
} ign_DemoUpdateLockActivities;

typedef struct _ign_DemoUpdateLockBattery {
    uint32_t battery;
} ign_DemoUpdateLockBattery;

typedef struct _ign_DemoUpdateLockStatus {
    uint32_t status;
} ign_DemoUpdateLockStatus;

typedef PB_BYTES_ARRAY_T(100) ign_LockEntry_ekey_t;
typedef struct _ign_LockEntry {
    char bt_id[100];
    ign_LockEntry_ekey_t ekey;
} ign_LockEntry;

typedef PB_BYTES_ARRAY_T(500) ign_LockJob_lock_cmd_t;
typedef struct _ign_LockJob {
    char bt_id[100];
    ign_LockJob_lock_cmd_t lock_cmd;
} ign_LockJob;

typedef PB_BYTES_ARRAY_T(1024) ign_LockLog_log_data_t;
typedef struct _ign_LockLog {
    char bt_id[100];
    ign_LockLog_log_data_t log_data;
} ign_LockLog;

typedef struct _ign_BridgeEventData {
    bool has_profile;
    ign_BridgeProfile profile;
    pb_callback_t bt_ids;
    pb_size_t lock_log_count;
    ign_LockLog lock_log[5];
    char demo_lockId[100];
    bool has_demo_update_lock_battery;
    ign_DemoUpdateLockBattery demo_update_lock_battery;
    bool has_demo_update_lock_status;
    ign_DemoUpdateLockStatus demo_update_lock_status;
    bool has_demo_update_lock_activities;
    ign_DemoUpdateLockActivities demo_update_lock_activities;
} ign_BridgeEventData;

typedef struct _ign_ServerEventData {
    pb_size_t lock_entries_count;
    ign_LockEntry lock_entries[5];
    bool has_job;
    ign_LockJob job;
    bool has_demo_job;
    ign_DemoLockJob demo_job;
} ign_ServerEventData;

typedef struct _ign_MsgInfo {
    uint32_t msg_id;
    uint32_t time;
    ign_EventType event_type;
    bool has_bridge_data;
    ign_BridgeEventData bridge_data;
    bool has_server_data;
    ign_ServerEventData server_data;
} ign_MsgInfo;


/* Helper constants for enums */
#define _ign_EventType_MIN ign_EventType_UNSPECIFIED
#define _ign_EventType_MAX ign_EventType_NEW_JOB_NOTIFY
#define _ign_EventType_ARRAYSIZE ((ign_EventType)(ign_EventType_NEW_JOB_NOTIFY+1))

#define _ign_OSType_MIN ign_OSType_UKNOWN
#define _ign_OSType_MAX ign_OSType_RTOS
#define _ign_OSType_ARRAYSIZE ((ign_OSType)(ign_OSType_RTOS+1))

#define _ign_DemoLockCommand_MIN ign_DemoLockCommand_UNSPECIFIED_DLC
#define _ign_DemoLockCommand_MAX ign_DemoLockCommand_GET_LOGS
#define _ign_DemoLockCommand_ARRAYSIZE ((ign_DemoLockCommand)(ign_DemoLockCommand_GET_LOGS+1))


/* Initializer values for message structs */
#define ign_MsgInfo_init_default                 {0, 0, _ign_EventType_MIN, false, ign_BridgeEventData_init_default, false, ign_ServerEventData_init_default}
#define ign_BridgeEventData_init_default         {false, ign_BridgeProfile_init_default, {{NULL}, NULL}, 0, {ign_LockLog_init_default, ign_LockLog_init_default, ign_LockLog_init_default, ign_LockLog_init_default, ign_LockLog_init_default}, "", false, ign_DemoUpdateLockBattery_init_default, false, ign_DemoUpdateLockStatus_init_default, false, ign_DemoUpdateLockActivities_init_default}
#define ign_BridgeProfile_init_default           {_ign_OSType_MIN, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, 0, 0, {0, {0}}}
#define ign_LockLog_init_default                 {"", {0, {0}}}
#define ign_DemoUpdateLockBattery_init_default   {0}
#define ign_DemoUpdateLockStatus_init_default    {0}
#define ign_DemoUpdateLockActivities_init_default {{0, {0}}}
#define ign_LockJob_init_default                 {"", {0, {0}}}
#define ign_LockEntry_init_default               {"", {0, {0}}}
#define ign_ServerEventData_init_default         {0, {ign_LockEntry_init_default, ign_LockEntry_init_default, ign_LockEntry_init_default, ign_LockEntry_init_default, ign_LockEntry_init_default}, false, ign_LockJob_init_default, false, ign_DemoLockJob_init_default}
#define ign_DemoLockJob_init_default             {"", _ign_DemoLockCommand_MIN, {0, {0}}}
#define ign_MsgInfo_init_zero                    {0, 0, _ign_EventType_MIN, false, ign_BridgeEventData_init_zero, false, ign_ServerEventData_init_zero}
#define ign_BridgeEventData_init_zero            {false, ign_BridgeProfile_init_zero, {{NULL}, NULL}, 0, {ign_LockLog_init_zero, ign_LockLog_init_zero, ign_LockLog_init_zero, ign_LockLog_init_zero, ign_LockLog_init_zero}, "", false, ign_DemoUpdateLockBattery_init_zero, false, ign_DemoUpdateLockStatus_init_zero, false, ign_DemoUpdateLockActivities_init_zero}
#define ign_BridgeProfile_init_zero              {_ign_OSType_MIN, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, 0, 0, {0, {0}}}
#define ign_LockLog_init_zero                    {"", {0, {0}}}
#define ign_DemoUpdateLockBattery_init_zero      {0}
#define ign_DemoUpdateLockStatus_init_zero       {0}
#define ign_DemoUpdateLockActivities_init_zero   {{0, {0}}}
#define ign_LockJob_init_zero                    {"", {0, {0}}}
#define ign_LockEntry_init_zero                  {"", {0, {0}}}
#define ign_ServerEventData_init_zero            {0, {ign_LockEntry_init_zero, ign_LockEntry_init_zero, ign_LockEntry_init_zero, ign_LockEntry_init_zero, ign_LockEntry_init_zero}, false, ign_LockJob_init_zero, false, ign_DemoLockJob_init_zero}
#define ign_DemoLockJob_init_zero                {"", _ign_DemoLockCommand_MIN, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define ign_BridgeProfile_os_info_tag            1
#define ign_BridgeProfile_bt_id_tag              2
#define ign_BridgeProfile_mac_addr_tag           3
#define ign_BridgeProfile_local_ip_tag           4
#define ign_BridgeProfile_public_ip_tag          5
#define ign_BridgeProfile_sys_statics_tag        6
#define ign_BridgeProfile_wifi_ssid_tag          7
#define ign_BridgeProfile_wifi_signal_tag        8
#define ign_BridgeProfile_inited_time_tag        9
#define ign_BridgeProfile_name_tag               10
#define ign_DemoLockJob_bt_id_tag                1
#define ign_DemoLockJob_op_cmd_tag               2
#define ign_DemoLockJob_pin_tag                  3
#define ign_DemoUpdateLockActivities_log_tag     1
#define ign_DemoUpdateLockBattery_battery_tag    1
#define ign_DemoUpdateLockStatus_status_tag      1
#define ign_LockEntry_bt_id_tag                  1
#define ign_LockEntry_ekey_tag                   2
#define ign_LockJob_bt_id_tag                    1
#define ign_LockJob_lock_cmd_tag                 2
#define ign_LockLog_bt_id_tag                    1
#define ign_LockLog_log_data_tag                 2
#define ign_BridgeEventData_profile_tag          1
#define ign_BridgeEventData_bt_ids_tag           2
#define ign_BridgeEventData_lock_log_tag         3
#define ign_BridgeEventData_demo_lockId_tag      4
#define ign_BridgeEventData_demo_update_lock_battery_tag 5
#define ign_BridgeEventData_demo_update_lock_status_tag 6
#define ign_BridgeEventData_demo_update_lock_activities_tag 7
#define ign_ServerEventData_lock_entries_tag     1
#define ign_ServerEventData_job_tag              2
#define ign_ServerEventData_demo_job_tag         3
#define ign_MsgInfo_msg_id_tag                   1
#define ign_MsgInfo_time_tag                     2
#define ign_MsgInfo_event_type_tag               3
#define ign_MsgInfo_bridge_data_tag              4
#define ign_MsgInfo_server_data_tag              5

/* Struct field encoding specification for nanopb */
#define ign_MsgInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   msg_id,            1) \
X(a, STATIC,   SINGULAR, UINT32,   time,              2) \
X(a, STATIC,   SINGULAR, UENUM,    event_type,        3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bridge_data,       4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  server_data,       5)
#define ign_MsgInfo_CALLBACK NULL
#define ign_MsgInfo_DEFAULT NULL
#define ign_MsgInfo_bridge_data_MSGTYPE ign_BridgeEventData
#define ign_MsgInfo_server_data_MSGTYPE ign_ServerEventData

#define ign_BridgeEventData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  profile,           1) \
X(a, CALLBACK, REPEATED, STRING,   bt_ids,            2) \
X(a, STATIC,   REPEATED, MESSAGE,  lock_log,          3) \
X(a, STATIC,   SINGULAR, STRING,   demo_lockId,       4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  demo_update_lock_battery,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  demo_update_lock_status,   6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  demo_update_lock_activities,   7)
#define ign_BridgeEventData_CALLBACK pb_default_field_callback
#define ign_BridgeEventData_DEFAULT NULL
#define ign_BridgeEventData_profile_MSGTYPE ign_BridgeProfile
#define ign_BridgeEventData_lock_log_MSGTYPE ign_LockLog
#define ign_BridgeEventData_demo_update_lock_battery_MSGTYPE ign_DemoUpdateLockBattery
#define ign_BridgeEventData_demo_update_lock_status_MSGTYPE ign_DemoUpdateLockStatus
#define ign_BridgeEventData_demo_update_lock_activities_MSGTYPE ign_DemoUpdateLockActivities

#define ign_BridgeProfile_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    os_info,           1) \
X(a, STATIC,   SINGULAR, BYTES,    bt_id,             2) \
X(a, STATIC,   SINGULAR, BYTES,    mac_addr,          3) \
X(a, STATIC,   SINGULAR, BYTES,    local_ip,          4) \
X(a, STATIC,   SINGULAR, BYTES,    public_ip,         5) \
X(a, STATIC,   SINGULAR, BYTES,    sys_statics,       6) \
X(a, STATIC,   SINGULAR, BYTES,    wifi_ssid,         7) \
X(a, STATIC,   SINGULAR, INT32,    wifi_signal,       8) \
X(a, STATIC,   SINGULAR, UINT32,   inited_time,       9) \
X(a, STATIC,   SINGULAR, BYTES,    name,             10)
#define ign_BridgeProfile_CALLBACK NULL
#define ign_BridgeProfile_DEFAULT NULL

#define ign_LockLog_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   bt_id,             1) \
X(a, STATIC,   SINGULAR, BYTES,    log_data,          2)
#define ign_LockLog_CALLBACK NULL
#define ign_LockLog_DEFAULT NULL

#define ign_DemoUpdateLockBattery_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   battery,           1)
#define ign_DemoUpdateLockBattery_CALLBACK NULL
#define ign_DemoUpdateLockBattery_DEFAULT NULL

#define ign_DemoUpdateLockStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   status,            1)
#define ign_DemoUpdateLockStatus_CALLBACK NULL
#define ign_DemoUpdateLockStatus_DEFAULT NULL

#define ign_DemoUpdateLockActivities_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    log,               1)
#define ign_DemoUpdateLockActivities_CALLBACK NULL
#define ign_DemoUpdateLockActivities_DEFAULT NULL

#define ign_LockJob_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   bt_id,             1) \
X(a, STATIC,   SINGULAR, BYTES,    lock_cmd,          2)
#define ign_LockJob_CALLBACK NULL
#define ign_LockJob_DEFAULT NULL

#define ign_LockEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   bt_id,             1) \
X(a, STATIC,   SINGULAR, BYTES,    ekey,              2)
#define ign_LockEntry_CALLBACK NULL
#define ign_LockEntry_DEFAULT NULL

#define ign_ServerEventData_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  lock_entries,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  job,               2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  demo_job,          3)
#define ign_ServerEventData_CALLBACK NULL
#define ign_ServerEventData_DEFAULT NULL
#define ign_ServerEventData_lock_entries_MSGTYPE ign_LockEntry
#define ign_ServerEventData_job_MSGTYPE ign_LockJob
#define ign_ServerEventData_demo_job_MSGTYPE ign_DemoLockJob

#define ign_DemoLockJob_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   bt_id,             1) \
X(a, STATIC,   SINGULAR, UENUM,    op_cmd,            2) \
X(a, STATIC,   SINGULAR, BYTES,    pin,               3)
#define ign_DemoLockJob_CALLBACK NULL
#define ign_DemoLockJob_DEFAULT NULL

extern const pb_msgdesc_t ign_MsgInfo_msg;
extern const pb_msgdesc_t ign_BridgeEventData_msg;
extern const pb_msgdesc_t ign_BridgeProfile_msg;
extern const pb_msgdesc_t ign_LockLog_msg;
extern const pb_msgdesc_t ign_DemoUpdateLockBattery_msg;
extern const pb_msgdesc_t ign_DemoUpdateLockStatus_msg;
extern const pb_msgdesc_t ign_DemoUpdateLockActivities_msg;
extern const pb_msgdesc_t ign_LockJob_msg;
extern const pb_msgdesc_t ign_LockEntry_msg;
extern const pb_msgdesc_t ign_ServerEventData_msg;
extern const pb_msgdesc_t ign_DemoLockJob_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ign_MsgInfo_fields &ign_MsgInfo_msg
#define ign_BridgeEventData_fields &ign_BridgeEventData_msg
#define ign_BridgeProfile_fields &ign_BridgeProfile_msg
#define ign_LockLog_fields &ign_LockLog_msg
#define ign_DemoUpdateLockBattery_fields &ign_DemoUpdateLockBattery_msg
#define ign_DemoUpdateLockStatus_fields &ign_DemoUpdateLockStatus_msg
#define ign_DemoUpdateLockActivities_fields &ign_DemoUpdateLockActivities_msg
#define ign_LockJob_fields &ign_LockJob_msg
#define ign_LockEntry_fields &ign_LockEntry_msg
#define ign_ServerEventData_fields &ign_ServerEventData_msg
#define ign_DemoLockJob_fields &ign_DemoLockJob_msg

/* Maximum encoded size of messages (where known) */
/* ign_MsgInfo_size depends on runtime parameters */
/* ign_BridgeEventData_size depends on runtime parameters */
#define ign_BridgeProfile_size                   733
#define ign_LockLog_size                         1128
#define ign_DemoUpdateLockBattery_size           6
#define ign_DemoUpdateLockStatus_size            6
#define ign_DemoUpdateLockActivities_size        503
#define ign_LockJob_size                         604
#define ign_LockEntry_size                       203
#define ign_ServerEventData_size                 1845
#define ign_DemoLockJob_size                     205

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
