/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "ign.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ign_MsgInfo, ign_MsgInfo, 4)


PB_BIND(ign_BridgeEventData, ign_BridgeEventData, 4)


PB_BIND(ign_BridgeProfile, ign_BridgeProfile, 2)


PB_BIND(ign_LockLog, ign_LockLog, 2)


PB_BIND(ign_LocksTestUpdate, ign_LocksTestUpdate, AUTO)


PB_BIND(ign_DemoUpdateLockBattery, ign_DemoUpdateLockBattery, AUTO)


PB_BIND(ign_DemoUpdateLockStatus, ign_DemoUpdateLockStatus, AUTO)


PB_BIND(ign_DemoUpdateLockActivities, ign_DemoUpdateLockActivities, 2)


PB_BIND(ign_LockJob, ign_LockJob, 2)


PB_BIND(ign_Ekey, ign_Ekey, 2)


PB_BIND(ign_LockEntry, ign_LockEntry, 2)


PB_BIND(ign_ServerEventData, ign_ServerEventData, 4)


PB_BIND(ign_DemoLockJob, ign_DemoLockJob, AUTO)






