/*
 * Generated by gdbus-codegen 2.48.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef ___ROOT_CODE_CWORK_AD_BRIDGE_BRIDGE_GATTLIB_DBUS_DBUS_BLUEZ_V5_48_ORG_BLUEZ_BATTERY1_H__
#define ___ROOT_CODE_CWORK_AD_BRIDGE_BRIDGE_GATTLIB_DBUS_DBUS_BLUEZ_V5_48_ORG_BLUEZ_BATTERY1_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.bluez.Battery1 */

#define TYPE_ORG_BLUEZ_BATTERY1 (org_bluez_battery1_get_type ())
#define ORG_BLUEZ_BATTERY1(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_BLUEZ_BATTERY1, OrgBluezBattery1))
#define IS_ORG_BLUEZ_BATTERY1(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_BLUEZ_BATTERY1))
#define ORG_BLUEZ_BATTERY1_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_BLUEZ_BATTERY1, OrgBluezBattery1Iface))

struct _OrgBluezBattery1;
typedef struct _OrgBluezBattery1 OrgBluezBattery1;
typedef struct _OrgBluezBattery1Iface OrgBluezBattery1Iface;

struct _OrgBluezBattery1Iface
{
  GTypeInterface parent_iface;


  guchar  (*get_percentage) (OrgBluezBattery1 *object);

  void (*properties_changed) (
    OrgBluezBattery1 *object,
    const gchar *arg_interface,
    GVariant *arg_changed_properties,
    const gchar *const *arg_invalidated_properties);

};

GType org_bluez_battery1_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_bluez_battery1_interface_info (void);
guint org_bluez_battery1_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus signal emissions functions: */
void org_bluez_battery1_emit_properties_changed (
    OrgBluezBattery1 *object,
    const gchar *arg_interface,
    GVariant *arg_changed_properties,
    const gchar *const *arg_invalidated_properties);



/* D-Bus property accessors: */
guchar org_bluez_battery1_get_percentage (OrgBluezBattery1 *object);
void org_bluez_battery1_set_percentage (OrgBluezBattery1 *object, guchar value);


/* ---- */

#define TYPE_ORG_BLUEZ_BATTERY1_PROXY (org_bluez_battery1_proxy_get_type ())
#define ORG_BLUEZ_BATTERY1_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_BLUEZ_BATTERY1_PROXY, OrgBluezBattery1Proxy))
#define ORG_BLUEZ_BATTERY1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_BLUEZ_BATTERY1_PROXY, OrgBluezBattery1ProxyClass))
#define ORG_BLUEZ_BATTERY1_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_BLUEZ_BATTERY1_PROXY, OrgBluezBattery1ProxyClass))
#define IS_ORG_BLUEZ_BATTERY1_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_BLUEZ_BATTERY1_PROXY))
#define IS_ORG_BLUEZ_BATTERY1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_BLUEZ_BATTERY1_PROXY))

typedef struct _OrgBluezBattery1Proxy OrgBluezBattery1Proxy;
typedef struct _OrgBluezBattery1ProxyClass OrgBluezBattery1ProxyClass;
typedef struct _OrgBluezBattery1ProxyPrivate OrgBluezBattery1ProxyPrivate;

struct _OrgBluezBattery1Proxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgBluezBattery1ProxyPrivate *priv;
};

struct _OrgBluezBattery1ProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_bluez_battery1_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgBluezBattery1Proxy, g_object_unref)
#endif

void org_bluez_battery1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgBluezBattery1 *org_bluez_battery1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgBluezBattery1 *org_bluez_battery1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_bluez_battery1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgBluezBattery1 *org_bluez_battery1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgBluezBattery1 *org_bluez_battery1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_BLUEZ_BATTERY1_SKELETON (org_bluez_battery1_skeleton_get_type ())
#define ORG_BLUEZ_BATTERY1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_BLUEZ_BATTERY1_SKELETON, OrgBluezBattery1Skeleton))
#define ORG_BLUEZ_BATTERY1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_BLUEZ_BATTERY1_SKELETON, OrgBluezBattery1SkeletonClass))
#define ORG_BLUEZ_BATTERY1_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_BLUEZ_BATTERY1_SKELETON, OrgBluezBattery1SkeletonClass))
#define IS_ORG_BLUEZ_BATTERY1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_BLUEZ_BATTERY1_SKELETON))
#define IS_ORG_BLUEZ_BATTERY1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_BLUEZ_BATTERY1_SKELETON))

typedef struct _OrgBluezBattery1Skeleton OrgBluezBattery1Skeleton;
typedef struct _OrgBluezBattery1SkeletonClass OrgBluezBattery1SkeletonClass;
typedef struct _OrgBluezBattery1SkeletonPrivate OrgBluezBattery1SkeletonPrivate;

struct _OrgBluezBattery1Skeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgBluezBattery1SkeletonPrivate *priv;
};

struct _OrgBluezBattery1SkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_bluez_battery1_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgBluezBattery1Skeleton, g_object_unref)
#endif

OrgBluezBattery1 *org_bluez_battery1_skeleton_new (void);


G_END_DECLS

#endif /* ___ROOT_CODE_CWORK_AD_BRIDGE_BRIDGE_GATTLIB_DBUS_DBUS_BLUEZ_V5_48_ORG_BLUEZ_BATTERY1_H__ */
