/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_IGN_IGN_PB_H_INCLUDED
#define PB_IGN_IGN_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _ign_EventType {
    ign_EventType_UNSPECIFIED = 0,
    ign_EventType_HEARTBEAT = 1,
    ign_EventType_LOCK_LOG = 2,
    ign_EventType_GET_USER_INFO = 3,
    ign_EventType_UPDATE_LOCK_STATUS = 4,
    ign_EventType_ADD_LOCK = 5,
    ign_EventType_GET_JOBS = 6,
    ign_EventType_UPDATE_JOB = 7,
    ign_EventType_UPDATE_USER_INFO = 128,
    ign_EventType_LOCK_JOB = 129
} ign_EventType;

typedef enum _ign_OSType {
    ign_OSType_UKNOWN = 0,
    ign_OSType_LINUX = 1,
    ign_OSType_RTOS = 2
} ign_OSType;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(100) ign_BridgeProfile_bt_id_t;
typedef PB_BYTES_ARRAY_T(100) ign_BridgeProfile_mac_addr_t;
typedef PB_BYTES_ARRAY_T(100) ign_BridgeProfile_local_ip_t;
typedef PB_BYTES_ARRAY_T(100) ign_BridgeProfile_public_ip_t;
typedef PB_BYTES_ARRAY_T(100) ign_BridgeProfile_sys_statics_t;
typedef PB_BYTES_ARRAY_T(100) ign_BridgeProfile_wifi_ssid_t;
typedef PB_BYTES_ARRAY_T(100) ign_BridgeProfile_name_t;
typedef struct _ign_BridgeProfile {
    ign_OSType os_info;
    ign_BridgeProfile_bt_id_t bt_id;
    ign_BridgeProfile_mac_addr_t mac_addr;
    ign_BridgeProfile_local_ip_t local_ip;
    ign_BridgeProfile_public_ip_t public_ip;
    ign_BridgeProfile_sys_statics_t sys_statics;
    ign_BridgeProfile_wifi_ssid_t wifi_ssid;
    int32_t wifi_signal;
    ign_BridgeProfile_name_t name;
    uint32_t inited_time;
} ign_BridgeProfile;

typedef struct _ign_LockEntry {
    char bt_id[100];
    pb_callback_t ekey;
} ign_LockEntry;

typedef struct _ign_LockJob {
    char bt_id[100];
    pb_callback_t lock_cmd;
} ign_LockJob;

typedef PB_BYTES_ARRAY_T(1024) ign_LockLog_log_data_t;
typedef struct _ign_LockLog {
    char bt_id[100];
    ign_LockLog_log_data_t log_data;
} ign_LockLog;

typedef struct _ign_BridgeEventData {
    bool has_profile;
    ign_BridgeProfile profile;
    pb_callback_t bt_ids;
    pb_callback_t logs;
} ign_BridgeEventData;

typedef struct _ign_ServerEventData {
    pb_callback_t lockEntries;
    bool has_job;
    ign_LockJob job;
} ign_ServerEventData;

typedef struct _ign_MsgInfo {
    uint32_t msg_id;
    uint32_t time;
    ign_EventType event_type;
    bool has_bridge_data;
    ign_BridgeEventData bridge_data;
    bool has_server_data;
    ign_ServerEventData server_data;
} ign_MsgInfo;


/* Helper constants for enums */
#define _ign_EventType_MIN ign_EventType_UNSPECIFIED
#define _ign_EventType_MAX ign_EventType_LOCK_JOB
#define _ign_EventType_ARRAYSIZE ((ign_EventType)(ign_EventType_LOCK_JOB+1))

#define _ign_OSType_MIN ign_OSType_UKNOWN
#define _ign_OSType_MAX ign_OSType_RTOS
#define _ign_OSType_ARRAYSIZE ((ign_OSType)(ign_OSType_RTOS+1))


/* Initializer values for message structs */
#define ign_MsgInfo_init_default                 {0, 0, _ign_EventType_MIN, false, ign_BridgeEventData_init_default, false, ign_ServerEventData_init_default}
#define ign_BridgeProfile_init_default           {_ign_OSType_MIN, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, 0, {0, {0}}, 0}
#define ign_LockLog_init_default                 {"", {0, {0}}}
#define ign_BridgeEventData_init_default         {false, ign_BridgeProfile_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define ign_LockJob_init_default                 {"", {{NULL}, NULL}}
#define ign_LockEntry_init_default               {"", {{NULL}, NULL}}
#define ign_ServerEventData_init_default         {{{NULL}, NULL}, false, ign_LockJob_init_default}
#define ign_MsgInfo_init_zero                    {0, 0, _ign_EventType_MIN, false, ign_BridgeEventData_init_zero, false, ign_ServerEventData_init_zero}
#define ign_BridgeProfile_init_zero              {_ign_OSType_MIN, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, 0, {0, {0}}, 0}
#define ign_LockLog_init_zero                    {"", {0, {0}}}
#define ign_BridgeEventData_init_zero            {false, ign_BridgeProfile_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}
#define ign_LockJob_init_zero                    {"", {{NULL}, NULL}}
#define ign_LockEntry_init_zero                  {"", {{NULL}, NULL}}
#define ign_ServerEventData_init_zero            {{{NULL}, NULL}, false, ign_LockJob_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ign_BridgeProfile_os_info_tag            1
#define ign_BridgeProfile_bt_id_tag              2
#define ign_BridgeProfile_mac_addr_tag           3
#define ign_BridgeProfile_local_ip_tag           4
#define ign_BridgeProfile_public_ip_tag          5
#define ign_BridgeProfile_sys_statics_tag        6
#define ign_BridgeProfile_wifi_ssid_tag          11
#define ign_BridgeProfile_wifi_signal_tag        12
#define ign_BridgeProfile_inited_time_tag        14
#define ign_BridgeProfile_name_tag               13
#define ign_LockEntry_bt_id_tag                  1
#define ign_LockEntry_ekey_tag                   2
#define ign_LockJob_bt_id_tag                    1
#define ign_LockJob_lock_cmd_tag                 2
#define ign_LockLog_bt_id_tag                    1
#define ign_LockLog_log_data_tag                 2
#define ign_BridgeEventData_profile_tag          1
#define ign_BridgeEventData_bt_ids_tag           2
#define ign_BridgeEventData_logs_tag             3
#define ign_ServerEventData_lockEntries_tag      1
#define ign_ServerEventData_job_tag              2
#define ign_MsgInfo_msg_id_tag                   1
#define ign_MsgInfo_time_tag                     2
#define ign_MsgInfo_event_type_tag               3
#define ign_MsgInfo_bridge_data_tag              4
#define ign_MsgInfo_server_data_tag              5

/* Struct field encoding specification for nanopb */
#define ign_MsgInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   msg_id,            1) \
X(a, STATIC,   SINGULAR, UINT32,   time,              2) \
X(a, STATIC,   SINGULAR, UENUM,    event_type,        3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bridge_data,       4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  server_data,       5)
#define ign_MsgInfo_CALLBACK NULL
#define ign_MsgInfo_DEFAULT NULL
#define ign_MsgInfo_bridge_data_MSGTYPE ign_BridgeEventData
#define ign_MsgInfo_server_data_MSGTYPE ign_ServerEventData

#define ign_BridgeProfile_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    os_info,           1) \
X(a, STATIC,   SINGULAR, BYTES,    bt_id,             2) \
X(a, STATIC,   SINGULAR, BYTES,    mac_addr,          3) \
X(a, STATIC,   SINGULAR, BYTES,    local_ip,          4) \
X(a, STATIC,   SINGULAR, BYTES,    public_ip,         5) \
X(a, STATIC,   SINGULAR, BYTES,    sys_statics,       6) \
X(a, STATIC,   SINGULAR, BYTES,    wifi_ssid,        11) \
X(a, STATIC,   SINGULAR, INT32,    wifi_signal,      12) \
X(a, STATIC,   SINGULAR, BYTES,    name,             13) \
X(a, STATIC,   SINGULAR, UINT32,   inited_time,      14)
#define ign_BridgeProfile_CALLBACK NULL
#define ign_BridgeProfile_DEFAULT NULL

#define ign_LockLog_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   bt_id,             1) \
X(a, STATIC,   SINGULAR, BYTES,    log_data,          2)
#define ign_LockLog_CALLBACK NULL
#define ign_LockLog_DEFAULT NULL

#define ign_BridgeEventData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  profile,           1) \
X(a, CALLBACK, REPEATED, STRING,   bt_ids,            2) \
X(a, CALLBACK, REPEATED, MESSAGE,  logs,              3)
#define ign_BridgeEventData_CALLBACK pb_default_field_callback
#define ign_BridgeEventData_DEFAULT NULL
#define ign_BridgeEventData_profile_MSGTYPE ign_BridgeProfile
#define ign_BridgeEventData_logs_MSGTYPE ign_LockLog

#define ign_LockJob_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   bt_id,             1) \
X(a, CALLBACK, SINGULAR, BYTES,    lock_cmd,          2)
#define ign_LockJob_CALLBACK pb_default_field_callback
#define ign_LockJob_DEFAULT NULL

#define ign_LockEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   bt_id,             1) \
X(a, CALLBACK, SINGULAR, BYTES,    ekey,              2)
#define ign_LockEntry_CALLBACK pb_default_field_callback
#define ign_LockEntry_DEFAULT NULL

#define ign_ServerEventData_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  lockEntries,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  job,               2)
#define ign_ServerEventData_CALLBACK pb_default_field_callback
#define ign_ServerEventData_DEFAULT NULL
#define ign_ServerEventData_lockEntries_MSGTYPE ign_LockEntry
#define ign_ServerEventData_job_MSGTYPE ign_LockJob

extern const pb_msgdesc_t ign_MsgInfo_msg;
extern const pb_msgdesc_t ign_BridgeProfile_msg;
extern const pb_msgdesc_t ign_LockLog_msg;
extern const pb_msgdesc_t ign_BridgeEventData_msg;
extern const pb_msgdesc_t ign_LockJob_msg;
extern const pb_msgdesc_t ign_LockEntry_msg;
extern const pb_msgdesc_t ign_ServerEventData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ign_MsgInfo_fields &ign_MsgInfo_msg
#define ign_BridgeProfile_fields &ign_BridgeProfile_msg
#define ign_LockLog_fields &ign_LockLog_msg
#define ign_BridgeEventData_fields &ign_BridgeEventData_msg
#define ign_LockJob_fields &ign_LockJob_msg
#define ign_LockEntry_fields &ign_LockEntry_msg
#define ign_ServerEventData_fields &ign_ServerEventData_msg

/* Maximum encoded size of messages (where known) */
/* ign_MsgInfo_size depends on runtime parameters */
#define ign_BridgeProfile_size                   733
#define ign_LockLog_size                         1128
/* ign_BridgeEventData_size depends on runtime parameters */
/* ign_LockJob_size depends on runtime parameters */
/* ign_LockEntry_size depends on runtime parameters */
/* ign_ServerEventData_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
