/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "ign.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ign_MsgInfo, ign_MsgInfo, 2)


PB_BIND(ign_BridgeProfile, ign_BridgeProfile, AUTO)


PB_BIND(ign_LockLog, ign_LockLog, 2)


PB_BIND(ign_BridgeEventData, ign_BridgeEventData, AUTO)


PB_BIND(ign_LockJob, ign_LockJob, AUTO)


PB_BIND(ign_ServerEventData, ign_ServerEventData, AUTO)





